### ISSUE TITLE
Data missed

### ISSUE THREAD

**Issue by s1530129650** [HLR/Cross_Modality_Relevance#5]
When I run "python run_cmr_nlvr2_test.py". The error is :

        traceback (most recent call last):
          File "run_cmr_nlvr2_test.py", line 86, in <module>
            shuffle=False, drop_last=False),
          File "run_cmr_nlvr2_test.py", line 53, in get_tuple
            dset = NLVR2Dataset(splits)
          File "/home/v-ensh/sciteamdrive2/v-ensh/CodeSearch/Cross_Modality_Relevance/data_preprocessing/cmr_nlvr2_data.py", line 18, in __init__
            self.data.extend(json.load(open(data_loc)))
        FileNotFoundError: [Errno 2] No such file or directory: '/tank/space/chen_zheng/data/cmr_nlvr2/data/nlvr2_preprocessing_data/test.json'

How could I obtain the data (`/tank/space/chen_zheng/data/cmr_nlvr2/data/nlvr2_preprocessing_data/test.json` set [here](https://github.com/HLR/Cross_Modality_Relevance/blob/ebb8bfcd0d96009b4fd7ecd372fe08961525130c/configs/global_config.py#L6-L8))

**Comment by kordjamshidi** [comment]
@czheng17 can help here

**Comment by czheng17** [comment]
We have released the data download link that is shown in our README file (the data link is https://github.com/lil-lab/nlvr.). Please download the data and follow our README description: `Before running the code, please make sure your config file is correct: configs/global_config.py.` (Here is important because you should write your data location in your machine after you download the data) Then you can correctly run `python run_cmr_nlvr2_test.py`.

**Comment by s1530129650** [comment]
Many thanks
